apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: spring-hello
  name: spring-hello-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: spring-hello
  template: 
    metadata: 
      labels: 
        app: spring-hello
    spec: 
      containers: 
        - name: spring-hello
          image: sravangcpdocker/spring-hello:1.0
          imagePullPolicy: Always
          ports: 
            - containerPort: 8080
