apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-hello
  name: simple-hello-deployment
  namespace: default
spec:
  ports:
  - nodePort: 31282
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-hello
  sessionAffinity: None
  type: LoadBalancer
